
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import {Header} from "@/widgets/header/header";
import Sidebar from "@/app/components/Sidebar";


const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        {/*{children}*/}
        <div style={{ display: 'flex', minHeight: '100vh' }}>

            {/* Наше фиксированное меню */}

            <Sidebar />

            {/* Область для контента текущей страницы */}
            <div style={{ flex: 1, marginLeft: '260px', backgroundColor: '#f0f2f5' }}>
                {children}
            </div>

        </div>
        </body>
        </html>
    );
}
